### ISSUE TITLE
Requisito 2: configuración de consola en Debug incompleta

### ISSUE THREAD

**Issue by LucioRuixo** [jctourret/Arkanoid_raylib#8]
En las propiedades de la configuración Debug, no hay nada configurado en "Vinculador > Sistema > Subsistema".
Este apartado debe especificar que el subsistema debe ser "CONSOLE".

![Screenshot_5](https://user-images.githubusercontent.com/54895404/67295172-29469a80-f4bd-11e9-80b4-96f9035f5462.png)

Luego, En "Vinculador > Avanzadas > Punto de entrada", se debe especificar que el punto de entrada es "mainCRTStartup".

![Screenshot_6](https://user-images.githubusercontent.com/54895404/67295243-411e1e80-f4bd-11e9-98cb-cb8a31f69884.png)

**Comment by LucioRuixo** [comment]
Otra vez mala mía xD, "mainCRTStartup" debe estar en Release, no en Debug. El punto de entrada de Debug es el que debe estar vacío. Si está vacío en Release no linkea.

**Comment by jctourret** [comment]
Gracias Lucio por la especificidad!
